using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
//Name: Sree Bandi & Daniel Rusetski 
//Date: November 12, 2020
//Assignment: ICS3U1 Culminating Assignment 
//Script Name: MainMenu
//Purpose of Script: Control the menu
public class MainMenu : MonoBehaviour//Auto-generated by Unity, MonoBehaviour is the base class from which every Unity script derives. See https://docs.unity3d.com/ScriptReference/MonoBehaviour.html.
{
    //This is a public method used to load in the first level. The void keyword is used in method signatures to declare a method that does not return a value.
    public void PlayMap1()
    {
        //Load in the scene mentioned.
        SceneManager.LoadScene("Lvl2");

    }
    //This is a public method used to be the quit command/exit. The void keyword is used in method signatures to declare a method that does not return a value.
    public void Quit()
    {
        //Closes the game. 
        Application.Quit();
    }
}
